resources:
  - name: rrv_image
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

  - name: rrv_repo
    type: GitRepo
    configuration:
      path: trriplejay/basic-node
      gitProvider: tr_github
      sha: master

pipelines:
  - name: tr_rrv_updates
    steps:
      - name: rrv_s1
        type: bash
        triggeredBy:
          resources:
            - rrv_repo
        execution:
          onExecute:
            - echo "blah"
            - cat $STEP_JSON_PATH
            - write_output rrv_image "stepId=$STEP_ID" "imageTag=latest"
        outputResources:
          - rrv_image
      - name: rrv_s2
        type: bash
        execution:
          onExecute:
            - echo "blah"
            - echo "stepId is - $res_rrv_image_stepId"
            - echo "imageTag is - $res_rrv_image_imageTag"
        triggeredBy:
          resources:
            - rrv_image
