resources:
  - name: myImage_basic
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

  - name: myOtherImage_basic
    type: Image
    configuration:
      registry: tr_docker
      imageName: trriplejay/simpleserver
      imageTag: latest

  - name: myRepo_basic
    type: GitRepo
    configuration:
      path: trriplejay/basic-node
      gitProvider: tr_github

pipelines:
  - name: tr_test_pipeline_1
    configuration:
      environmentVariables:
        readOnly:
          testReadOnly: "successful!"
    steps:
      - name: basic_step
        type: Bash
        configuration:
          affinityGroup: test_group
          # inputResources:
          #   - name: myRepo_basic
          #   - name: myImage_basic
          #     trigger: false
          outputResources:
            - name: myOtherImage_basic
        execution:
          onStart:
            - retry_command echo "here we go!!!"
            - echo "what is this"
          onExecute:
            - echo "read only value issssss $testReadOnly"
            - echo "$step_url"
            - docker ps -a
            - docker inspect reqProc
            - echo "Hello world!"
            - echo "step json at $STEP_JSON_PATH"
            - cat $STEP_JSON_PATH |  jq '.'
            - for item in ${!open_group_info[@]}; do echo "$item --- ${open_group_info[$item]}"; done
            - cat /jfrog/status/step.env
          onSuccess:
            - echo "yay success"
            - printenv | grep myRepo_basic
            - printenv | grep myImage_basic
            - printenv | sort
          onFailure:
            - echo "boo failure"
          onComplete:
            - echo "done"

      - name: fail_in_start
        type: Bash
        configuration:
          integrations:
            - name: tr_github
          inputSteps:
            - name: basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
            - echo "attempting to set readOnly variable"
            - export testReadOnly="foobar"
            - cat badfile
            - echo "we continue after failure"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_exec
        type: Bash
        configuration:
          integrations:
            - name: tr_github
          inputSteps:
            - name: basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - cat badfile
            - echo "we continue after failure"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_onsucc
        type: Bash
        configuration:
          affinityGroup: test_group
          integrations:
            - name: tr_github
          inputResources:
            - name: myOtherImage_basic
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
            - cat badfile
            - echo "we continue after failure"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_onfail
        type: Bash
        configuration:
          integrations:
            - name: tr_github
          inputSteps:
            - name: basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - cat badfile
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
            - cat badfile
            - echo "we continue after failure"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"

      - name: fail_in_oncomp
        type: Bash
        configuration:
          integrations:
            - name: tr_github
          inputSteps:
            - name: basic_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"
            - cat badfile
            - echo "we continue after failure"
          onCancel:
            - echo "Someone cancelled the job"

  # - name: tr_pipeline_bad
  #   steps:
  #     - name: bad_step
  #       type: Bash
  #       requires:
  #         integrations:
  #           - name: not_real
